mpris: Only import 'indicate' if $DISPLAY is set
This avoids printing of the following error message:

    ImportError: could not import gtk.gdk

Fixes #311