Require at least cycleopts 4.3
With any version lower I get the following errors in the tests:
```
tests/_app/test_cli.py:5: in <module>
    from mopidy._app import cli
src/mopidy/_app/cli.py:57: in <module>
    @Parameter(
../.venv/lib/python3.14/site-packages/cyclopts/utils.py:56: in new_init
    original_init(self, *args, **kwargs)
E   TypeError: Parameter.__init__() got an unexpected keyword argument 'n_tokens'
```